// Auto-generated by update_data.py -- DO NOT EDIT MANUALLY
// Last updated: 2026-04-09 09:17 HKT
// KPI_DATA: 8 indicators | NEWS_DATA: 0 items | JOBS_DATA: 0 listings

const LAST_UPDATED = "2026-04-09 09:17 HKT";

// KPI_DATA: HSI and Fed Rate are fetched live every run.
// All others: edit values in the MANUAL KPIs section above, commit, and push.
const KPI_DATA = {
  "gdp_growth": {
    "label": "GDP Growth",
    "val": "3.5%",
    "delta": "up +1.0pp YoY",
    "delta_class": "positive",
    "period": "Full-year 2025 . C&SD",
    "url": "https://www.info.gov.hk/gia/general/202601/30/P2026013000262.htm"
  },
  "unemployment": {
    "label": "Unemployment",
    "val": "3.8%",
    "delta": "down prev 3.9%",
    "delta_class": "positive",
    "period": "Dec25-Feb26 . C&SD",
    "url": "https://www.censtatd.gov.hk/en/scode210.html"
  },
  "pmi": {
    "label": "PMI (Mar 2026)",
    "val": "49.3",
    "delta": "down -4.0 from Feb",
    "delta_class": "negative",
    "period": "Mar 2026 . S&P Global",
    "url": "https://www.spglobal.com/marketintelligence/en/mi/research-analysis/purchasing-managers-index.html",
    "caution": true
  },
  "hsi": {
    "label": "Hang Seng Index",
    "val": "N/A",
    "delta": "N/A",
    "delta_class": "neutral",
    "period": "09 Apr 2026 . HSI",
    "url": "https://www.hsi.com.hk"
  },
  "cpi": {
    "label": "CPI Inflation",
    "val": "1.7%",
    "delta": "up +0.6pp from Jan",
    "delta_class": "neutral",
    "period": "Feb 2026 . HKSAR",
    "url": "https://www.hkeconomy.gov.hk/en/situation/development/index.htm"
  },
  "job_vacancies": {
    "label": "Job Vacancies",
    "val": "46,000",
    "delta": "down -21% YoY",
    "delta_class": "negative",
    "period": "Dec 2025 . C&SD",
    "url": "https://www.censtatd.gov.hk/en/scode210.html",
    "caution": true
  },
  "median_wage": {
    "label": "Median Monthly Wage",
    "val": "HK$21,200",
    "delta": "up +3.5% YoY",
    "delta_class": "positive",
    "period": "2025 . Ambition HK",
    "url": "https://www.austcham.com.hk/member-news/future-hiring-hong-kong-2026"
  },
  "fed_rate": {
    "label": "US Fed Rate",
    "val": "4.25-4.50%",
    "delta": "held at target range",
    "delta_class": "neutral",
    "period": "Latest . Federal Reserve",
    "url": "https://www.federalreserve.gov/monetarypolicy/openmarket.htm"
  }
};

const NEWS_DATA = [];

const JOBS_DATA = [];
