// ============================================
// HK Job Market Terminal — Data Layer
// All dashboard data lives here. Regenerated by refresh.py
// ============================================

const META = {
  updated: "09 Apr 2026 10:24 HKT",
  version: "v2026.04"
};

const KPI_DATA = [
  {
    label: "GDP Growth",
    value: "3.5%",
    delta: "▲ +1.0pp YoY",
    deltaClass: "positive",
    period: "Full-year 2025",
    source: "C&SD",
    sourceUrl: "https://www.info.gov.hk/gia/general/202601/30/P2026013000262.htm",
    valueClass: ""
  },
  {
    label: "Unemployment",
    value: "3.8%",
    delta: "▼ -0.1pp",
    deltaClass: "positive",
    period: "Dec 25 – Feb 26",
    source: "C&SD",
    sourceUrl: "https://www.censtatd.gov.hk/en/scode210.html",
    valueClass: ""
  },
  {
    label: "PMI (Dec 25)",
    value: "51.9",
    delta: "▲ vs Nov (52.9)",
    deltaClass: "neutral",
    period: "Expansion zone",
    source: "S&P Global",
    sourceUrl: "https://tradingeconomics.com/hong-kong/manufacturing-pmi",
    valueClass: ""
  },
  {
    label: "Hang Seng",
    value: "24,751",
    delta: "— latest available",
    deltaClass: "neutral",
    period: "30 Mar 2026",
    source: "Trading Economics (HK50)",
    sourceUrl: "https://tradingeconomics.com/hong-kong/stock-market",
    valueClass: ""
  },
  {
    label: "CPI Inflation",
    value: "1.7%",
    delta: "▲ +0.6pp from Jan",
    deltaClass: "neutral",
    period: "Feb 2026",
    source: "HKSAR Govt",
    sourceUrl: "https://www.hkeconomy.gov.hk/en/situation/development/index.htm",
    valueClass: ""
  },
  {
    label: "Job Vacancies",
    value: "46,000",
    delta: "▼ -21% YoY",
    deltaClass: "negative",
    period: "Dec 2025",
    source: "C&SD",
    sourceUrl: "https://www.censtatd.gov.hk/en/scode210.html",
    valueClass: "caution"
  },
  {
    label: "Median Wage",
    value: "HK$21,200",
    delta: "▲ +3.5% YoY",
    deltaClass: "positive",
    period: "May–Jun 2025",
    source: "C&SD (info.gov.hk)",
    sourceUrl: "https://www.info.gov.hk/gia/general/202603/23/P2026032300370.htm",
    valueClass: ""
  },
  {
    label: "US Fed Rate",
    value: "3.50%–3.75%",
    delta: "— held Mar 26",
    deltaClass: "neutral",
    period: "Target range · Mar 2026",
    source: "Trading Economics / Fed",
    sourceUrl: "https://tradingeconomics.com/united-states/interest-rate",
    valueClass: ""
  }
];

const SIGNAL_DATA = [
  {
    title: "Financial Services Hiring +10-15%",
    desc: "IPO boom (HK$103B+ in Q1 alone, #1 globally) and fintech VC surging 2.3x to US$638M are driving strong demand for compliance, risk, and data professionals in banking.",
    sentiment: "positive",
    sourceLabel: "SCMP via LinkedIn",
    sourceUrl: "https://www.linkedin.com/posts/peggy-sito-06165126_hiring-outlook-improves-for-hong-kongs-financial-activity-7396758655511126016-xtIw"
  },
  {
    title: "AI/Data Specialists: 15-25% Salary Premium",
    desc: "1 in 4 companies can't fill AI roles. Data governance, ML engineering, and cybersecurity professionals command premium compensation while generalist roles face oversupply.",
    sentiment: "positive",
    sourceLabel: "KOS International",
    sourceUrl: "https://www.kos-intl.com/insight/the-ai-talent-gap-in-hong-kong-is-real-heres-what-smart-employers-are-doing-about-it/"
  },
  {
    title: "PMI Shock: Mar 2026 Contraction at 49.3",
    desc: "After a 35-month high in Feb (53.3), March PMI dropped sharply into contraction territory. Geopolitical shocks and tariff uncertainty are weighing on business confidence.",
    sentiment: "caution",
    sourceLabel: "C&SD / HKSAR Govt",
    sourceUrl: "https://www.info.gov.hk/gia/general/202601/30/P2026013000262.htm"
  },
  {
    title: "Job Vacancies Down 21% — Structural Paradox",
    desc: "46,000 vacancies vs 134,700 unemployed. Only finance/insurance vacancies grew (+16% YoY). The market is bifurcating: high-skill roles thrive while routine positions vanish.",
    sentiment: "negative",
    sourceLabel: "HK Economy",
    sourceUrl: "https://www.hkeconomy.gov.hk/en/situation/development/index.htm"
  },
  {
    title: "Data Governance Regulation Expanding",
    desc: "Critical Infrastructure cybersecurity law in force since Jan 2026. PDPO mandatory breach notification incoming. AI governance legislation under review. All drive demand for DPO/governance roles.",
    sentiment: "positive",
    sourceLabel: "SCMP",
    sourceUrl: "https://www.scmp.com/news/hong-kong/society/article/3342754/hong-kong-plans-revive-privacy-law-mandating-firms-report-data-breaches"
  },
  {
    title: "US Tariff Regime Remains Unpredictable",
    desc: "SCOTUS struck down IEEPA tariffs but 10% Section 122 remains. Trump-Xi Beijing meeting occurred Apr 2026 but trade truce is fragile. Section 301 investigation now covers HK.",
    sentiment: "caution",
    sourceLabel: "Bloomberg Law",
    sourceUrl: "https://news.bloomberglaw.com/international-trade/china-stocks-in-hong-kong-jump-as-us-court-strikes-down-tariffs"
  }
];

const HK_MACRO_DATA = [
  {
    indicator: "GDP Growth",
    current: "3.5% (2025)",
    currentClass: "",
    previous: "2.5% (2024)",
    trend: "▲ UP",
    trendClass: "positive",
    implication: "12th consecutive quarter of expansion. Strongest annual growth since 2017 (ex-rebound). Driven by AI electronics exports and financial services. Government forecasts 2.5-3.5% for 2026.",
    sourceLabel: "C&SD",
    sourceUrl: "https://www.info.gov.hk/gia/general/202601/30/P2026013000262.htm"
  },
  {
    indicator: "Unemployment Rate",
    current: "3.8%",
    currentClass: "",
    previous: "3.9% (Nov-Jan)",
    trend: "▼ DOWN",
    trendClass: "positive",
    implication: "Near full employment. 134,700 persons unemployed with 46,000 vacancies. Finance/insurance sector strongest with vacancies growing +16% YoY.",
    sourceLabel: "C&SD",
    sourceUrl: "https://www.censtatd.gov.hk/en/scode210.html"
  },
  {
    indicator: "CPI Inflation",
    current: "1.7% (Feb 26)",
    currentClass: "",
    previous: "1.1% (Jan 26)",
    trend: "▲ MILD",
    trendClass: "neutral",
    implication: "Benign inflation supports real wage growth. Well below global averages. Government forecasts underlying CPI at 1.7% for 2026, keeping cost of hiring talent relatively stable.",
    sourceLabel: "HKSAR",
    sourceUrl: "https://www.hkeconomy.gov.hk/en/situation/development/index.htm"
  },
  {
    indicator: "PMI (Mar 2026)",
    current: "49.3",
    currentClass: "caution",
    previous: "53.3 (Feb, 35-mo high)",
    trend: "▼ CONTRACTION",
    trendClass: "negative",
    implication: "Sharp reversal from expansion. Geopolitical shock signal. New orders and export orders likely contracted. Businesses may freeze hiring decisions in the near term pending clarity on tariff policy.",
    sourceLabel: "S&P Global",
    sourceUrl: "https://www.markiteconomics.com"
  },
  {
    indicator: "Hang Seng Index",
    current: "25,848",
    currentClass: "",
    previous: "28,056 (Jan peak)",
    trend: "~ MIXED",
    trendClass: "neutral",
    implication: "-2% YTD after Jan peak, but +2.91% on Apr 8. Market sentiment volatile. Financial sector hiring remains positive thanks to IPO pipeline with 500+ applications in 2025.",
    sourceLabel: "HSI",
    sourceUrl: "https://www.hsi.com.hk"
  },
  {
    indicator: "Office Vacancy (Central)",
    current: "9.9%",
    currentClass: "",
    previous: "~10%+ (Jan 26)",
    trend: "▼ DOWN",
    trendClass: "positive",
    implication: "26-month low. IPO-linked financial firms taking prime Central space. Lower costs give businesses room to invest in headcount. \"Flight to quality\" trend benefits talent attraction.",
    sourceLabel: "JLL",
    sourceUrl: "https://realestateasia.com/commercial-office/news/hong-kong-grade-office-rents-decline-5-in-2026"
  },
  {
    indicator: "Median Monthly Wage",
    current: "HK$21,200",
    currentClass: "",
    previous: "HK$20,500 (2024)",
    trend: "▲ UP",
    trendClass: "positive",
    implication: "+3.5% YoY real wage growth. Job movers earn 10-15% premiums. High-demand AI/data specialists command 15-25%+ premiums. Salary budget growth projected at ~4% for 2026.",
    sourceLabel: "Ambition",
    sourceUrl: "https://www.austcham.com.hk/member-news/future-hiring-hong-kong-2026"
  },
  {
    indicator: "Job Vacancies",
    current: "46,000",
    currentClass: "caution",
    previous: "58,410 (Dec 2024)",
    trend: "▼ DOWN",
    trendClass: "negative",
    implication: "-21% YoY decline. Only finance/insurance showed growth (+16%). Retail, accommodation, and food services saw largest drops. Structural mismatch between job seeker skills and available roles.",
    sourceLabel: "C&SD",
    sourceUrl: "https://www.censtatd.gov.hk/en/scode210.html"
  },
  {
    indicator: "Population",
    current: "7.51M",
    currentClass: "",
    previous: "7.50M (mid-2024)",
    trend: "~ STABLE",
    trendClass: "neutral",
    implication: "+0.1% growth. Net inflow 29,100 offset by natural decline of 18,900. Talent schemes (TTPS, QMAS) bringing in skilled workers. Emigration wave has stabilized.",
    sourceLabel: "C&SD",
    sourceUrl: "https://www.censtatd.gov.hk"
  },
  {
    indicator: "IPO Market",
    current: "HK$103B+ (Q1 26)",
    currentClass: "",
    previous: "HK$286B (FY2025)",
    trend: "▲ STRONG",
    trendClass: "positive",
    implication: "#1 globally in Q1 2026. 500+ listing applications in 2025. Drives hiring across investment banking, compliance, legal, accounting, and corporate governance.",
    sourceLabel: "HKEX",
    sourceUrl: "https://www.hkex.com.hk"
  },
  {
    indicator: "Bank Capital Ratio",
    current: "25.1%",
    currentClass: "",
    previous: "Well above 8% min",
    trend: "— STABLE",
    trendClass: "positive",
    implication: "Banking sector well-capitalized. However, NPL ratio elevated at 2.01% (20-yr avg: 0.93%), requiring robust credit risk and compliance teams.",
    sourceLabel: "HKMA",
    sourceUrl: "https://www.hkma.gov.hk/eng/news-and-media/press-releases/2026/03/20260330-4/"
  },
  {
    indicator: "Fintech VC",
    current: "US$638M (2025)",
    currentClass: "",
    previous: "US$274M (2024)",
    trend: "▲ +2.3x",
    trendClass: "positive",
    implication: "Fintech investment surged 2.3x. HKMA Fintech 2030 Blueprint pushes AI, DLT, data excellence. 95% of banks already using fintech. Creates sustained demand for specialist tech roles.",
    sourceLabel: "HKMA",
    sourceUrl: "https://www.hkma.gov.hk/media/eng/doc/key-information/press-release/2026/20260203e3a1.pdf"
  }
];

const GLOBAL_DATA = [
  {
    indicator: "US Federal Funds Rate",
    current: "3.50-3.75%",
    currentClass: "",
    previous: "Held Mar 2026",
    trend: "— HOLD",
    trendClass: "neutral",
    implication: "HKD pegged to USD, so HK rates follow the Fed. 1 cut projected for 2026. Lower rates would ease borrowing costs, supporting business expansion and hiring. Current rate maintains tight financial conditions.",
    sourceLabel: "Federal Reserve",
    sourceUrl: "https://www.federalreserve.gov"
  },
  {
    indicator: "China GDP Growth",
    current: "5.0% (FY2025)",
    currentClass: "",
    previous: "4.5% (Q4 2025 QoQ)",
    trend: "~ SOFTENING",
    trendClass: "neutral",
    implication: "China hit its official target but Q4 decelerated. Mainland firms expanding into HK provide a demand channel for compliance, legal, and finance talent. Property sector drag is a downside risk.",
    sourceLabel: "NBS China",
    sourceUrl: "https://www.stats.gov.cn"
  },
  {
    indicator: "China PMI (Mar 2026)",
    current: "50.4",
    currentClass: "",
    previous: "Back in expansion",
    trend: "▲ UP",
    trendClass: "positive",
    implication: "Official NBS PMI returned to expansion at 50.4 in March. Supports cross-border trade and GBA economic integration. Positive for HK logistics, trade finance, and professional services roles.",
    sourceLabel: "NBS China",
    sourceUrl: "https://www.stats.gov.cn"
  },
  {
    indicator: "USD/HKD Exchange",
    current: "7.837",
    currentClass: "",
    previous: "Peg band: 7.75-7.85",
    trend: "— STABLE",
    trendClass: "positive",
    implication: "HKD peg intact within the band. No pressure on the Linked Exchange Rate System. Stability supports foreign business confidence and international talent attraction.",
    sourceLabel: "HKMA",
    sourceUrl: "https://www.hkma.gov.hk"
  },
  {
    indicator: "US-China Tariffs",
    current: "10% (Section 122)",
    currentClass: "caution",
    previous: "IEEPA voided by SCOTUS",
    trend: "⚠ ELEVATED",
    trendClass: "negative",
    implication: "SCOTUS struck down IEEPA tariffs (Feb 2026) but 10% Section 122 tariff remains for 150 days. Section 301 forced labor investigation now covers HK. Trade uncertainty keeps hiring cautious in export-dependent sectors.",
    sourceLabel: "Bloomberg",
    sourceUrl: "https://news.bloomberglaw.com/international-trade/china-stocks-in-hong-kong-jump-as-us-court-strikes-down-tariffs"
  },
  {
    indicator: "US-China Diplomacy",
    current: "Trump-Xi Apr 2026",
    currentClass: "",
    previous: "KL Joint Arrangement Nov 25",
    trend: "~ FRAGILE",
    trendClass: "neutral",
    implication: "US-China Kuala Lumpur Joint Arrangement set 10% reciprocal tariff, suspended 100% escalation until Nov 2026. Trump visited Beijing Mar 31-Apr 2. Progress would ease supply chain uncertainty and accelerate HK hiring.",
    sourceLabel: "The Standard",
    sourceUrl: "https://www.thestandard.com.hk/china/article/324913/Trump-to-travel-to-China-next-month-with-US-tariffs-in-focus"
  },
  {
    indicator: "Global AI Capex 2026",
    current: "US$527B",
    currentClass: "",
    previous: "US$2.9T infra through 2028",
    trend: "▲ SURGING",
    trendClass: "positive",
    implication: "Hyperscaler AI capital expenditure consensus at US$527B for 2026. HK positioned as Asia's AI finance and governance hub. Drives demand for AI governance, risk management, and data science professionals.",
    sourceLabel: "HKSTP",
    sourceUrl: "https://www.hkstp.org/en/park-life/news-and-events/news/hkstp-career-fair-2026-reimagine-ai-plus"
  },
  {
    indicator: "GBA Integration",
    current: "Accelerating",
    currentClass: "",
    previous: "15th 5-Year Plan launched",
    trend: "▲ DEEPENING",
    trendClass: "positive",
    implication: "China's 15th Five-Year Plan endorses HK as \"super connector.\" MTR Shenzhen expansion by 2035. Cross-border private car scheme launched. Creates new career pathways for bilingual professionals with GBA exposure.",
    sourceLabel: "Beijing Review",
    sourceUrl: "https://www.bjreview.com/China/202603/t20260316_800433003.html"
  },
  {
    indicator: "HK Talent Schemes",
    current: "TTPS expanded to 200 unis",
    currentClass: "",
    previous: "184 previously",
    trend: "▲ EXPANDING",
    trendClass: "positive",
    implication: "TTPS Category A stay extended to 3 years. 90-day visa renewal window for 6 schemes. Digital verification cutting processing to 9-14 days. Broadens talent pipeline, especially in AI, fintech, ESG.",
    sourceLabel: "LeapScholar",
    sourceUrl: "https://leapscholar.com/digest/news-hong-kong-top-talent-pass-scheme-2026-2027"
  }
];

const NEWS_DATA = [
  {
    headline: "FTAHK制定港2030目標：助金融業AI應用率達90% 吸引逾百億投資 [FTAHK Sets 2030 Target: 90% AI Adoption Rate Across All HK Financial Institutions, Attracting HK$8-12B Investment]",
    date: "2026-04-03",
    source: "FTAHK / 金融科技協會",
    url: "https://www.ftahk.org",
    category: "FINTECH",
    impact: "The Hong Kong Fintech Association (FTAHK) released a position paper setting 2030 targets: 90% AI adoption across all financial institutions (up from current 38%), HK$8–12B in AI-related venture investment, 75+ new AI-native financial products, and top-3 global ranking in financial AI innovation. A survey of 103 institutions found 49% struggling to recruit technical talent and 74% demanding clearer AI ethics guidance. This roadmap will directly create a sustained 5-year hiring boom for AI engineers, model validators, compliance specialists, and fintech product managers in Hong Kong's financial sector.",
    sentiment: "positive"
  },
  {
    headline: "China Launches Investigations into US Trade Practices; Escalation Risk for HK",
    date: "2026-04-02",
    source: "Reuters / SCMP",
    url: "https://www.scmp.com/economy/china-economy/article/3342754",
    category: "TRADE & GEOPOLITICS",
    impact: "China launched investigations into US practices that 'disrupt global supply chains' and 'hinder green product trade.' Scheduled to conclude in 6 months. Could reignite trade uncertainty.",
    sentiment: "negative"
  },
  {
    headline: "Trump-Xi Beijing Summit: Trade Truce Fragile but Markets Rally",
    date: "2026-04-02",
    source: "The Standard",
    url: "https://www.thestandard.com.hk/china/article/324913/Trump-to-travel-to-China-next-month-with-US-tariffs-in-focus",
    category: "TRADE & GEOPOLITICS",
    impact: "Trump visited Beijing Mar 31 - Apr 2, 2026. Markets rallied but no concrete tariff reduction announced. The Kuala Lumpur Joint Arrangement still holds: 10% reciprocal tariff with the 100% escalation suspended until November 2026. Fragile stability means businesses continue cautious hiring while deferring major expansion decisions.",
    sentiment: "neutral"
  },
  {
    headline: "HK Economy Grew 3.5% in 2025; CPI Forecast at 1.7% for 2026",
    date: "2026-04-01",
    source: "HKSAR Government Economist",
    url: "https://www.hkeconomy.gov.hk/en/situation/development/index.htm",
    category: "GLOBAL",
    impact: "Third consecutive year of expansion. Merchandise exports surged 29.6% YoY in Jan-Feb 2026 driven by AI electronics. Low inflation supports real wage growth and stable hiring costs.",
    sentiment: "positive"
  },
  {
    headline: "China's NBS PMI Returns to Expansion at 50.4 in March 2026",
    date: "2026-03-31",
    source: "NBS China",
    url: "https://www.stats.gov.cn",
    category: "CHINA MAINLAND",
    impact: "Official NBS Manufacturing PMI rose to 50.4 in March, returning to expansion after 2 months of contraction. New orders and production subindices improved. Positive signal for GBA manufacturing and cross-border trade, supporting HK's role as trade finance and professional services hub.",
    sentiment: "positive"
  },
  {
    headline: "AI Talent Gap Real: 1 in 4 HK Companies Can't Fill AI Roles, Salary Premiums 15-25%",
    date: "2026-03-30",
    source: "KOS International",
    url: "https://www.kos-intl.com/insight/the-ai-talent-gap-in-hong-kong-is-real-heres-what-smart-employers-are-doing-about-it/",
    category: "TECHNOLOGY & AI",
    impact: "Structural split: generalist roles face oversupply, while AI/ML/data/cybersecurity specialists command 15-25% salary premiums. Over half of employers introduced AI with headcount optimisation as primary goal.",
    sentiment: "neutral"
  },
  {
    headline: "HKMA Financial Stability Report: Banking Sector Risks Monitored Amid Trade Tensions",
    date: "2026-03-30",
    source: "HKMA",
    url: "https://www.hkma.gov.hk/eng/news-and-media/press-releases/2026/03/20260330-4/",
    category: "FINANCIAL SECTOR",
    impact: "Broadly stable local banking sector but ongoing global trade tension risks. Keeps demand elevated for risk, compliance, and regulatory affairs roles at banks.",
    sentiment: "neutral"
  },
  {
    headline: "香港失業率升至3.9% 高盛警告AI永久裁員潮逼近 [Hong Kong Unemployment Rate Rises to 3.9%; Goldman Sachs Warns AI-Driven Permanent Layoff Wave Approaching]",
    date: "2026-03-30",
    source: "HK01 / 經濟日報",
    url: "https://www.hk01.com",
    category: "LOCAL EMPLOYMENT",
    impact: "Hong Kong's seasonally adjusted unemployment rate rose to 3.9% in the November 2025–January 2026 period, translating to approximately 138,400 unemployed persons — the highest in several years. Goldman Sachs' 2026 global report warns that AI deployment maturity in finance and tech sectors is shifting from job augmentation to job substitution, particularly threatening mid-level white-collar roles. Youth unemployment is particularly elevated. If AI-driven structural unemployment accelerates, the city faces the prospect of entrenched joblessness for professionals who cannot reskill rapidly.",
    sentiment: "negative"
  },
  {
    headline: "內地科技公司競相登陸香港 BBC：香港成「中企出海橋頭堡」 [Mainland Tech Companies Race to Set Up in Hong Kong; BBC: HK Becomes 'Launchpad for Chinese Tech Going Global']",
    date: "2026-03-29",
    source: "BBC中文 / 信報",
    url: "https://www.bbc.com/zhongwen",
    category: "TECHNOLOGY & AI",
    impact: "Mainland Chinese tech listings on HKEX surged 153% from 30 in 2024 to 76 in 2025, as geopolitical barriers in the US and EU push Chinese AI, robotics, and software firms to use Hong Kong as a regulatory sandbox and international capital gateway. MiningLamp Technology (AI software), Yunji Technology (service robots), and numerous AI firms are establishing HK operations to build compliance credentials for global expansion. This structural shift is creating material demand for bilingual tech talent, compliance specialists, and cross-border data governance professionals in Hong Kong.",
    sentiment: "positive"
  },
  {
    headline: "公務員事務局：2026年首輪綜合招聘考試3月28日起接受報名 [Civil Service Bureau: Applications for 2026 Round One Common Recruitment Exam Open from 28 March]",
    date: "2026-03-28",
    source: "政府新聞公報 (GIS)",
    url: "https://www.info.gov.hk/gia/general/202603/28/P2026032800123.htm",
    category: "LOCAL EMPLOYMENT",
    impact: "Despite the overall civil service contraction, the Civil Service Bureau opened applications for the 2026 Common Recruitment Examination (CRE) from 28 March to 10 April, with the exam scheduled for 6 June 2026. This entry pathway for degree-level civil service positions (Administrative Officers, Executive Officers, disciplinary services) remains a significant channel for Hong Kong graduates, particularly amid private sector uncertainty. The continued holding of CRE despite headcount cuts signals that selective quality hiring into key government grades is maintained.",
    sentiment: "neutral"
  },
  {
    headline: "港交所AI主題ETF日均成交額突破五億 [HKEX AI-Themed ETF Daily Turnover Exceeds HK$500M]",
    date: "2026-03-27",
    source: "經濟日報 HKET",
    url: "https://www.hket.com",
    category: "FINANCIAL SECTOR",
    impact: "AI-themed ETF trading on HKEX surged past HK$500M daily average, making the AI sector the hottest thematic cluster by turnover. This reflects strong investor conviction in HK's AI ecosystem development and validates the commercial case for AI governance and compliance infrastructure in the financial sector.",
    sentiment: "positive"
  },
  {
    headline: "HKPC 'Revamp & Grow' Programme: 800+ SMEs Supported with HK$3B+ Digital Transformation",
    date: "2026-03-25",
    source: "HKPC",
    url: "https://www.hkpc.org/en/revamp-and-grow",
    category: "TECHNOLOGY & AI",
    impact: "HKPC expanded its digital transformation programme supporting 800+ SMEs with over HK$3B in aggregate tech investment. The programme focuses on AI deployment, Industry 4.0, and cybersecurity — creating indirect demand for tech consultants, AI engineers, and data governance advisors serving the SME segment.",
    sentiment: "positive"
  },
  {
    headline: "HKMA Fintech 2030 Blueprint: AI, DLT, Data Excellence to Transform Banking",
    date: "2026-03-22",
    source: "HKMA",
    url: "https://www.hkma.gov.hk/media/eng/doc/key-information/press-release/2026/20260203e3a1.pdf",
    category: "FINTECH",
    impact: "HKMA published its 'Fintech 2030 Blueprint' prioritising AI integration in banking operations, distributed ledger technology for settlement systems, and data excellence standards. 95% of banks are already using fintech. This regulatory push ensures sustained demand for fintech specialists, data engineers, and AI governance professionals in the banking sector through at least 2030.",
    sentiment: "positive"
  },
  {
    headline: "香港私營機構職位空缺降至46,000個（按年跌21%）",
    date: "2026-03-20",
    source: "巴士的報（引述政府統計處）",
    url: "https://www.bastillepost.com/global/article/5706034-private-sector-employment-and-vacancies-decline-in-december-2025-reports-census-and-statistics-department",
    category: "LOCAL EMPLOYMENT",
    impact: "政府統計處公布2025年12月私營機構職位空缺約46,000個，較上年同期減少21%（-12,410）。金融及保險業空缺則按年增加。",
    sentiment: "negative"
  },
  {
    headline: "ERB推出2026年度「先聘用後培訓」計劃 [ERB Launches 2026 'Hire-Then-Train' Programme]",
    date: "2026-03-20",
    source: "僱員再培訓局 (ERB)",
    url: "https://www.erb.org",
    category: "LOCAL EMPLOYMENT",
    impact: "ERB expanded its placement-first training model covering digital marketing, elderly care, logistics technology, and AI-assisted customer service. Employers commit to hiring candidates before training begins, significantly improving employment outcomes. This is a key government mechanism to bridge the structural skills gap, particularly for mid-career professionals transitioning away from declining sectors.",
    sentiment: "positive"
  },
  {
    headline: "Hong Kong IPO Pipeline Surges: 500+ Listing Applications as Market Reclaims Global #1",
    date: "2026-03-20",
    source: "SCMP / HKEX",
    url: "https://www.scmp.com/business/companies/article/3342780/hong-kong-reclaims-worlds-top-ipo-market",
    category: "FINANCIAL SECTOR",
    impact: "HKEX received 500+ listing applications in 2025 and raised HK$103B+ in Q1 2026 alone, reclaiming #1 globally. China Harbour Holdings, logistics SPACs, and tech unicorns are driving the pipeline. Massive demand for investment bankers, compliance specialists, lawyers, accountants, and corporate governance professionals.",
    sentiment: "positive"
  },
  {
    headline: "人行減息0.25厘 刺激大灣區經濟 [PBoC Cuts Rates 0.25% to Stimulate GBA Economy]",
    date: "2026-03-18",
    source: "文匯報 / 央行",
    url: "https://www.wenweipo.com",
    category: "CHINA MAINLAND",
    impact: "PBoC cut the 1-year loan prime rate by 25bp to stimulate economic activity. The easing benefits GBA cross-border business and may encourage mainland companies to expand HK operations, indirectly supporting professional services hiring in Hong Kong.",
    sentiment: "positive"
  },
  {
    headline: "15th Five-Year Plan Endorses HK as GBA 'Super Connector'",
    date: "2026-03-18",
    source: "Beijing Review / Xinhua",
    url: "https://www.bjreview.com/China/202603/t20260316_800433003.html",
    category: "CHINA MAINLAND",
    impact: "China's 15th Five-Year Plan (2026-2030) formally designates HK as the GBA's 'super connector' for international finance, trade, and technology. MTR expansion to Shenzhen, cross-border private car scheme, and mutual recognition of professional qualifications are accelerating. Bilingual professionals with GBA network exposure are in highest demand.",
    sentiment: "positive"
  },
  {
    headline: "HK Unemployment Falls to 3.8%: Labour Market Tightens in Finance, Loosens in Retail",
    date: "2026-03-18",
    source: "C&SD / HKSAR Govt",
    url: "https://www.censtatd.gov.hk/en/scode210.html",
    category: "POLICY & REGULATION",
    impact: "Seasonally adjusted rate fell from 3.9% (Nov-Jan) to 3.8% (Dec-Feb). Financial services unemployment at historic low of 1.2%. But retail/accommodation/F&B unemployment elevated at 5.5-6.2%. Stark bifurcation between knowledge-economy and service-sector employment.",
    sentiment: "positive"
  },
  {
    headline: "勞工處4月起加強餐飲、零售、建造業招聘及就業服務",
    date: "2026-03-16",
    source: "政府新聞公報 (info.gov.hk)",
    url: "https://www.info.gov.hk/gia/general/202603/16/P2026031600237.htm",
    category: "LOCAL EMPLOYMENT",
    impact: "勞工處宣布4月1日起，10間就業中心會加強為餐飲、零售及建造業提供招聘及就業服務，並安排更多地區招聘會及招聘周，另於4月21日、5月12日及5月13日舉辦大型行業招聘會。",
    sentiment: "neutral"
  },
  {
    headline: "Hong Kong Cybersecurity Law (Critical Infrastructure) Takes Effect January 2026",
    date: "2026-03-15",
    source: "SCMP / GIS",
    url: "https://www.scmp.com/news/hong-kong/law-and-crime/article/3297523/hong-kongs-cybersecurity-law-critical-infrastructure",
    category: "DATA GOVERNANCE & PRIVACY",
    impact: "The Protection of Critical Infrastructures (Computer Systems) Ordinance came into force in January 2026, mandating cybersecurity measures for designated critical infrastructure operators across banking, energy, transport, healthcare, and communications. Non-compliance carries heavy penalties. This creates immediate and sustained demand for cybersecurity professionals, compliance officers, IT auditors, and data protection officers across all critical sectors.",
    sentiment: "positive"
  },
  {
    headline: "PDPO Reform: Mandatory Data Breach Notification on the Horizon",
    date: "2026-03-14",
    source: "SCMP / PCPD",
    url: "https://www.scmp.com/news/hong-kong/society/article/3342754/hong-kong-plans-revive-privacy-law-mandating-firms-report-data-breaches",
    category: "DATA GOVERNANCE & PRIVACY",
    impact: "Hong Kong's Privacy Commissioner confirmed plans to amend the Personal Data (Privacy) Ordinance to introduce mandatory breach notification requirements, aligning HK with GDPR and mainland China's PIPL standards. This will force every data-handling organisation in HK to establish incident response teams and Data Protection Officer functions, directly boosting demand for governance, risk, and compliance (GRC) professionals.",
    sentiment: "positive"
  },
  {
    headline: "逾2900個優質職位空缺將於『職場新視野招聘會』提供",
    date: "2026-03-10",
    source: "政府新聞公報 (info.gov.hk)",
    url: "https://www.info.gov.hk/gia/general/202603/09/P2026030900300.htm",
    category: "LOCAL EMPLOYMENT",
    impact: "勞工處於3月12至13日在旺角麥花臣場館舉辦招聘會，逾60間機構提供超過2900個職位空缺（其中近2300個來自飲食、零售及運輸），多數月薪介乎12,000至25,000港元。",
    sentiment: "positive"
  },
  {
    headline: "香港薪酬指南2026：科技金融治理崗位嚴重人才短缺 加薪幅度3-5% [HK Salary Guide 2026: Critical Talent Shortages in Tech, Finance & Governance Roles; 3-5% Pay Rise Forecast]",
    date: "2026-03-10",
    source: "Morgan McKinley / 明報",
    url: "https://www.morganmckinley.com/hk/salary-guide",
    category: "LOCAL EMPLOYMENT",
    impact: "Morgan McKinley's 2026 HK Salary Guide identifies critical talent shortages in AI, data analytics, cybersecurity, cloud solutions, and governance roles, with general salary budgets capped at 3-5% but niche specialists commanding 10-20% premiums on job moves. The market is bifurcated: generalists face intense competition for limited openings while specialists in digital transformation and risk compliance are actively headhunted. Employers are increasingly prioritising skills-based and contract hiring, reducing reliance on permanent headcount expansion and signalling a more fluid labour market structure.",
    sentiment: "neutral"
  },
  {
    headline: "Section 301 Investigation Extended to Hong Kong: Forced Labour Concerns",
    date: "2026-03-10",
    source: "USTR / Reuters",
    url: "https://ustr.gov/issue-areas/enforcement/section-301-investigations",
    category: "US TARIFFS",
    impact: "USTR expanded the Section 301 forced labour investigation scope to include Hong Kong-origin goods and re-exports. This could lead to targeted tariffs or import bans on specific HK-re-exported products. Increases compliance burden on logistics and trade companies, driving demand for trade compliance specialists.",
    sentiment: "negative"
  },
  {
    headline: "AI Governance Standards: HK Joins Global Race with Proposed AI Ethics Framework",
    date: "2026-03-08",
    source: "GIS / ITIB",
    url: "https://www.info.gov.hk/gia/general/202603/08/P2026030800200.htm",
    category: "DATA GOVERNANCE & PRIVACY",
    impact: "Innovation, Technology and Industry Bureau (ITIB) announced a proposed AI ethical governance framework for public consultation. Drawing on EU AI Act principles and China's interim AI measures, the framework would require risk assessment for high-impact AI systems. Creates direct demand for AI governance specialists, ethics officers, and regulatory affairs roles.",
    sentiment: "positive"
  },
  {
    headline: "HK Science Park Career Fair 2026: 3,000+ AI & Innovation Roles Showcased",
    date: "2026-03-08",
    source: "HKSTP",
    url: "https://www.hkstp.org/en/park-life/news-and-events/news/hkstp-career-fair-2026-reimagine-ai-plus",
    category: "TECHNOLOGY & AI",
    impact: "HKSTP's career fair featured 120+ companies offering 3,000+ roles in AI, biotech, fintech, and deep tech. Salary ranges for AI/ML engineers: HK$40,000-80,000 monthly. The event signals robust tech sector hiring despite broader market uncertainty.",
    sentiment: "positive"
  },
  {
    headline: "金管局發出第四批虛擬銀行牌照意向書 [HKMA Issues Fourth Batch of Virtual Bank Licence Letters of Intent]",
    date: "2026-03-05",
    source: "HKMA / 明報",
    url: "https://www.hkma.gov.hk/eng/news-and-media/press-releases/2026/03/20260305-3/",
    category: "FINTECH",
    impact: "HKMA signalled expansion of the virtual banking ecosystem with a fourth batch of licence letters of intent, potentially adding 3-4 new digital banks. Each new virtual bank typically creates 100-200 technology, compliance, and operations roles. Combined with the existing 8 licensed virtual banks, this deepens HK's digital financial infrastructure and talent demand.",
    sentiment: "positive"
  },
  {
    headline: "Hiring Outlook Improves for Hong Kong's Financial Sector in 2026",
    date: "2026-03-05",
    source: "SCMP via LinkedIn",
    url: "https://www.linkedin.com/posts/peggy-sito-06165126_hiring-outlook-improves-for-hong-kongs-financial-activity-7396758655511126016-xtIw",
    category: "FINANCIAL SECTOR",
    impact: "Financial sector hiring sentiment strongest in 3 years. Private equity, hedge funds, and compliance teams are expanding. A-share listings in HK creating demand for Mandarin-English bilingual professionals in research, sales, and advisory.",
    sentiment: "positive"
  },
  {
    headline: "Global AI Infrastructure Capex to Reach US$527B in 2026",
    date: "2026-03-05",
    source: "Dell'Oro Group / Reuters",
    url: "https://www.delloro.com/news/ai-infrastructure-investment-forecast-2026/",
    category: "TECHNOLOGY & AI",
    impact: "Hyperscaler AI capex consensus at US$527B for 2026, with cumulative global AI infrastructure investment projected at US$2.9T through 2028. HK positioned as Asia's AI finance hub benefits from spillover hiring in AI governance, data engineering, and cloud architecture.",
    sentiment: "positive"
  },
  {
    headline: "HK Budget 2026-27: Government Freezes Civil Service Headcount, Invests in Digital Economy",
    date: "2026-03-02",
    source: "HKSAR Budget / GIS",
    url: "https://www.budget.gov.hk/2026/eng/budget03.html",
    category: "POLICY & REGULATION",
    impact: "Government will freeze civil service positions (currently ~190,000) while redirecting investment to digital economy infrastructure: HK$5B+ for AI research centres, smart city infrastructure, and cyber academy expansion. The freeze signals austerity in public sector hiring, but digital economy investment should generate private-sector demand in tech, data, and governance roles.",
    sentiment: "neutral"
  },
  {
    headline: "HK Government Approves Top Talent Pass Scheme Expansion to 200 Universities",
    date: "2026-03-01",
    source: "HKSAR Labour & Welfare Bureau",
    url: "https://leapscholar.com/digest/news-hong-kong-top-talent-pass-scheme-2026-2027",
    category: "POLICY & REGULATION",
    impact: "TTPS Category A now covers graduates from 200 globally ranked universities (up from 184). Category A stay extended to 3 years. 90-day pre-expiry renewal window for all 6 talent schemes. Digital verification cutting processing to 9-14 days. Makes HK more competitive for international AI, finance, and tech talent.",
    sentiment: "positive"
  },
  {
    headline: "Central Office Vacancy Rate Drops to 26-Month Low at 9.9%",
    date: "2026-02-28",
    source: "JLL / Real Estate Asia",
    url: "https://realestateasia.com/commercial-office/news/hong-kong-grade-office-rents-decline-5-in-2026",
    category: "REAL ESTATE & COST",
    impact: "Grade A Central vacancy fell to 9.9%, the lowest since December 2023. IPO-linked financial firms and mainland tech companies are the primary demand drivers. Lower rents (-5% YoY) give employers room to invest savings into headcount. 'Flight to quality' trend means firms upgrading space while maintaining or growing team sizes.",
    sentiment: "positive"
  },
  {
    headline: "Mainland Chinese Tech Listings on HKEX Surge 153% in 2025",
    date: "2026-02-25",
    source: "HKEX / SCMP",
    url: "https://www.hkex.com.hk",
    category: "CHINA MAINLAND",
    impact: "76 mainland tech companies listed on HKEX in 2025 (vs 30 in 2024), driven by US/EU geopolitical barriers. Each listing requires HK-based compliance, legal, investor relations, and data governance teams. Structural demand driver for professional services talent.",
    sentiment: "positive"
  },
  {
    headline: "SCOTUS Strikes Down IEEPA Tariffs; 10% Section 122 Remains",
    date: "2026-02-20",
    source: "Bloomberg Law",
    url: "https://news.bloomberglaw.com/international-trade/china-stocks-in-hong-kong-jump-as-us-court-strikes-down-tariffs",
    category: "US TARIFFS",
    impact: "US Supreme Court ruled IEEPA-based tariffs unconstitutional (Feb 2026). However, 10% blanket Section 122 tariff on all imports remains for 150 days. Hong Kong stocks jumped 3-4% on the ruling. Reduced but not eliminated trade barrier — partial relief for HK export-oriented businesses.",
    sentiment: "positive"
  },
  {
    headline: "Salary Budgets in HK Expected to Grow 4% in 2026: Mercer Survey",
    date: "2026-02-20",
    source: "Mercer / Ambition",
    url: "https://www.austcham.com.hk/member-news/future-hiring-hong-kong-2026",
    category: "CORPORATE",
    impact: "Mercer's 2026 Total Remuneration Survey projects 4% salary budget growth across HK. Top increases in technology (+5.2%), financial services (+4.8%), and healthcare (+4.5%). Counter-offers rising as specialist retention becomes critical. Benefits packages expanding to include AI-skilling allowances.",
    sentiment: "positive"
  },
  {
    headline: "裁員與結業齊發：香港踏入2026年的寒冬警號 [Layoffs and Closures Converge: Hong Kong Enters 2026 Under Winter Warning Signs]",
    date: "2026-02-11",
    source: "HK01 / 明報",
    url: "https://www.hk01.com",
    category: "LOCAL EMPLOYMENT",
    impact: "A wave of closures and layoffs at the start of 2026 has hit Hong Kong across multiple sectors: international architecture firm Benoy abruptly shut its HK office with 50 immediate job losses; Cathay Pacific announced limited layoffs cutting non-operational costs by ~5%; Citigroup cut ~1,000 employees in Asia. Retail and F&B closures (Pizza-BOX, 一碗肉燥, 老媽拌麵) have displaced frontline and grassroots workers. Unemployment rose from 3.2% (Q1 2025) to 3.8% (Q4 2025), with F&B unemployment hitting 6.2% and construction 6.7%, indicating structural deterioration in blue-collar segments.",
    sentiment: "negative"
  },
  {
    headline: "法定最低工資擬上調至每小時43.10元，最快5月1日生效",
    date: "2026-02-10",
    source: "RTHK",
    url: "https://gbcode.rthk.hk/TuniS/news.rthk.hk/rthk/en/component/k2/1843350-20260210.htm",
    category: "POLICY & REGULATION",
    impact: "行政會議接納最低工資委員會建議，把現行每小時42.10元上調至43.10元（+2.38%），待立法會通過後最快於2026年5月1日實施。",
    sentiment: "positive"
  },
  {
    headline: "Fintech VC Investment in HK Surges 2.3x to US$638M in 2025",
    date: "2026-02-05",
    source: "HKMA / InvestHK",
    url: "https://www.investhk.gov.hk/en/investment-opportunities/fintech.html",
    category: "FINTECH",
    impact: "Fintech venture capital investment in Hong Kong surged from US$274M in 2024 to US$638M in 2025, a 2.3x increase. Key areas: AI-native financial tools, blockchain infrastructure, and regulatory technology. Startups are aggressively hiring for data engineers, compliance analysts, and product managers.",
    sentiment: "positive"
  },
  {
    headline: "零售服務業就業人口自2018年底大跌21% 部分行業呈「無就業式增長」 [Retail & Hospitality Employment Down 21% Since End-2018; Some Sectors Show 'Jobless Growth']",
    date: "2026-01-19",
    source: "明報 / HKU經濟學家",
    url: "https://www.mingpao.com",
    category: "LOCAL EMPLOYMENT",
    impact: "A Ming Pao data analysis found that HK's retail, accommodation, and F&B employment fell 21% from end-2018 to November 2025, reaching 490,000 workers — a loss of 130,000 jobs in these traditionally accessible sectors. Despite rising retail sales values, sector employment continues to decline due to structural shifts toward high-end economic transformation, favouring finance and tech over labour-intensive services. HKU economist Tang Sik-wai described the pattern as 'jobless growth', warning that low-skilled workers face severe difficulty transitioning to finance and tech positions without significant re-training support.",
    sentiment: "negative"
  }
];

const JOBS_DATA = [
  {
    title: "Head of Data Protection Office",
    company: "Standard Chartered Bank",
    location: "Central, Hong Kong",
    salary: "HK$120K–160K/mo",
    desc: "Lead data protection strategy, PDPO compliance, cross-border data transfer governance, and AI ethics framework implementation across APAC operations.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/head-of-data-protection-office",
    posted: "2d ago"
  },
  {
    title: "AI Governance Manager",
    company: "HSBC",
    location: "Quarry Bay, Hong Kong",
    salary: "HK$80K–110K/mo",
    desc: "Develop and implement AI governance policies for retail and commercial banking. Ensure model risk management compliance. Partner with data science teams on responsible AI deployment.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/ai-governance-manager-hsbc",
    posted: "3d ago"
  },
  {
    title: "Data Governance Lead - Financial Services",
    company: "Deloitte",
    location: "Central, Hong Kong",
    salary: "HK$65K–90K/mo",
    desc: "Lead data governance advisory engagements for banking and insurance clients. Define data quality frameworks, metadata management, and PDPO/PIPL cross-border compliance strategies.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/data-governance-lead-deloitte",
    posted: "1w ago"
  },
  {
    title: "VP, Data Privacy & Compliance",
    company: "JP Morgan",
    location: "Cheung Kong Center, Central",
    salary: "Not disclosed",
    desc: "Oversee APAC data privacy programme. Drive PDPO reform readiness. Manage cross-functional data mapping and third-party vendor risk assessments.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/vp-data-privacy-jp-morgan",
    posted: "4d ago"
  },
  {
    title: "Senior Data Governance Analyst",
    company: "Bank of China (Hong Kong)",
    location: "Central, Hong Kong",
    salary: "HK$45K–65K/mo",
    desc: "Implement data governance standards for BOCHK group. Manage data lineage, data quality monitoring, and regulatory reporting data controls.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/senior-data-governance-analyst-bochk",
    posted: "5d ago"
  },
  {
    title: "Chief Data Officer (CDO)",
    company: "WeLab Bank",
    location: "Wong Chuk Hang, Hong Kong",
    salary: "HK$150K–200K/mo",
    desc: "Define enterprise data strategy for virtual bank operations. Lead data platform, AI model governance, and customer data monetisation while ensuring regulatory compliance.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/cdo-welab-bank",
    posted: "6d ago"
  },
  {
    title: "Data Protection Officer",
    company: "AIA Group",
    location: "AIA Central, Central",
    salary: "HK$90K–130K/mo",
    desc: "Serve as statutory DPO for AIA's HK operations. Lead privacy impact assessments, breach response, and cross-border data transfer compliance for insurance operations.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/dpo-aia-group",
    posted: "1w ago"
  },
  {
    title: "IT Governance & Risk Manager",
    company: "MTR Corporation",
    location: "Kowloon Bay, Hong Kong",
    salary: "HK$55K–75K/mo",
    desc: "Manage IT governance framework aligned with critical infrastructure cybersecurity law. Oversee IT risk assessments, vendor security compliance, and data governance controls.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/it-governance-risk-mtr",
    posted: "1w ago"
  },
  {
    title: "Manager, AI Ethics & Responsible Innovation",
    company: "Cathay Group",
    location: "Cathay City, Lantau",
    salary: "HK$55K–70K/mo",
    desc: "Establish AI ethics guidelines for aviation and loyalty programme AI applications. Conduct algorithmic impact assessments and develop explainability standards.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/ai-ethics-manager-cathay",
    posted: "3d ago"
  },
  {
    title: "Senior Compliance Analyst - Data & AI",
    company: "FWD Group",
    location: "Kowloon East, Hong Kong",
    salary: "HK$40K–55K/mo",
    desc: "Monitor compliance of AI-driven underwriting and claims models. Ensure adherence to HKIA guidelines and PDPO data usage requirements.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/senior-compliance-analyst-fwd",
    posted: "5d ago"
  },
  {
    title: "Data Governance Specialist",
    company: "Hong Kong Exchanges and Clearing (HKEX)",
    location: "Exchange Square, Central",
    salary: "HK$50K–70K/mo",
    desc: "Design and implement data governance policies for market data systems. Partner with technology teams on data lineage, quality standards, and regulatory data compliance.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/data-governance-specialist-hkex",
    posted: "2d ago"
  },
  {
    title: "Privacy Counsel - APAC",
    company: "Meta Platforms",
    location: "Taikoo Place, Quarry Bay",
    salary: "Not disclosed",
    desc: "Provide legal counsel on PDPO, PIPL, and regional privacy regulations. Support product teams on privacy-by-design implementation for APAC market features.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/privacy-counsel-apac-meta",
    posted: "4d ago"
  },
  {
    title: "Associate Director, Data Risk Management",
    company: "Credit Suisse (UBS Group)",
    location: "IFC, Central",
    salary: "HK$85K–120K/mo",
    desc: "Lead data risk identification and mitigation across wealth management and investment banking operations. Implement data loss prevention controls and regulatory data standards.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/ad-data-risk-ubs",
    posted: "1w ago"
  },
  {
    title: "Regulatory Technology (RegTech) Manager",
    company: "ZA Bank",
    location: "Kwun Tong, Kowloon",
    salary: "HK$60K–85K/mo",
    desc: "Lead RegTech implementation for virtual banking compliance. Deploy AI-powered AML/KYC systems and automated regulatory reporting solutions.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/regtech-manager-za-bank",
    posted: "6d ago"
  },
  {
    title: "Data Quality & Governance Lead",
    company: "Manulife",
    location: "Tsim Sha Tsui, Hong Kong",
    salary: "HK$55K–80K/mo",
    desc: "Establish enterprise data quality KPIs and governance operating model for insurance operations across HK and Macau. Partner with actuarial teams on data integrity for pricing models.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/data-quality-lead-manulife",
    posted: "3d ago"
  },
  {
    title: "Information Security Governance Officer",
    company: "Hospital Authority",
    location: "Various, Hong Kong",
    salary: "HK$50K–70K/mo",
    desc: "Implement information security governance framework compliant with critical infrastructure cybersecurity ordinance for healthcare. Oversee patient data protection and system access controls.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/infosec-governance-ha",
    posted: "5d ago"
  },
  {
    title: "ESG Data Governance Analyst",
    company: "BlackRock",
    location: "Two Pacific Place, Admiralty",
    salary: "HK$45K–60K/mo",
    desc: "Govern ESG data ingestion, validation, and reporting across APAC portfolios. Ensure data lineage and quality for climate risk models and sustainable investment analytics.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/esg-data-governance-blackrock",
    posted: "1w ago"
  },
  {
    title: "Cloud Data Governance Architect",
    company: "Hang Seng Bank",
    location: "Des Voeux Road, Central",
    salary: "HK$70K–100K/mo",
    desc: "Design cloud-native data governance architecture on AWS/Azure for banking data platform migration. Define data classification, encryption, and access control standards.",
    source: "JobsDB",
    url: "https://hk.jobsdb.com/job/cloud-data-governance-hang-seng",
    posted: "4d ago"
  },
  {
    title: "Director, AI & Data Governance",
    company: "PwC Hong Kong",
    location: "One International Finance Centre, Central",
    salary: "HK$100K–150K/mo",
    desc: "Lead AI governance advisory practice for financial services clients. Develop responsible AI frameworks, model risk management standards, and data ethics policies.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/director-ai-data-governance-pwc",
    posted: "1d ago"
  },
  {
    title: "VP, Enterprise Data Governance",
    company: "Goldman Sachs",
    location: "Cheung Kong Center, Central",
    salary: "Not disclosed",
    desc: "Drive enterprise-wide data governance strategy across engineering, operations, and compliance. Own data cataloguing, lineage, and quality programs for APAC.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/vp-enterprise-data-governance-goldman-sachs",
    posted: "2d ago"
  },
  {
    title: "AI Risk & Compliance Manager",
    company: "Hang Seng Bank",
    location: "Central, Hong Kong",
    salary: "HK$65K–90K/mo",
    desc: "Manage AI model risk inventory and compliance validation. Implement responsible AI standards aligned with HKMA guidance and internal risk appetite.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/ai-risk-compliance-manager-hang-seng",
    posted: "3d ago"
  },
  {
    title: "Head of Data Governance - APAC",
    company: "Citi",
    location: "Champion Tower, Kowloon",
    salary: "HK$130K–180K/mo",
    desc: "Lead regional data governance organisation for Citi's APAC businesses. Define data ownership framework, data steward network, and regulatory data management for 12 APAC markets.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/head-data-governance-apac-citi",
    posted: "4d ago"
  },
  {
    title: "Senior Manager, Privacy & Data Protection",
    company: "EY",
    location: "One Taikoo Place, Quarry Bay",
    salary: "HK$70K–100K/mo",
    desc: "Lead privacy consulting engagements across sectors. Advise on PDPO reform readiness, PIPL cross-border compliance, and privacy-by-design implementation.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/senior-manager-privacy-ey",
    posted: "3d ago"
  },
  {
    title: "Data Ethics Officer",
    company: "HKMA (Secondment)",
    location: "Two International Finance Centre, Central",
    salary: "HK$80K–110K/mo",
    desc: "Secondment role supporting HKMA's Fintech 2030 initiative. Develop data ethics standards for supervised institutions and coordinate cross-regulator AI governance frameworks.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/data-ethics-officer-hkma",
    posted: "5d ago"
  },
  {
    title: "Machine Learning Governance Lead",
    company: "Nomura",
    location: "One Island East, Quarry Bay",
    salary: "HK$75K–100K/mo",
    desc: "Build ML model governance framework for quantitative trading and risk management. Establish model validation, bias testing, and explainability standards.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/ml-governance-lead-nomura",
    posted: "1w ago"
  },
  {
    title: "Chief Privacy Officer",
    company: "Klook",
    location: "Kwun Tong, Kowloon",
    salary: "Not disclosed",
    desc: "Oversee global privacy programme for travel-tech platform. Manage PDPO, GDPR, and PIPL compliance across 25+ markets. Lead privacy engineering and data governance teams.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/chief-privacy-officer-klook",
    posted: "2d ago"
  },
  {
    title: "Compliance Officer - AI & Digital Assets",
    company: "OSL Digital Securities",
    location: "Cyberport, Hong Kong",
    salary: "HK$50K–75K/mo",
    desc: "Ensure compliance of AI-powered trading systems and digital asset products with SFC and HKMA regulations. Monitor algorithmic trading governance.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/compliance-officer-ai-osl",
    posted: "4d ago"
  },
  {
    title: "Data Governance Consultant",
    company: "Accenture",
    location: "One IFC, Central",
    salary: "HK$50K–75K/mo",
    desc: "Design and implement data governance solutions for banking clients. Specialise in metadata management, data cataloguing, and regulatory compliance automation.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/data-governance-consultant-accenture",
    posted: "6d ago"
  },
  {
    title: "APAC Data Protection Lead",
    company: "Prudential plc",
    location: "Victoria Dockside, TST",
    salary: "HK$90K–120K/mo",
    desc: "Lead data protection strategy across 12 APAC markets. Harmonise privacy compliance frameworks for insurance operations with focus on HK, mainland China, and Southeast Asia.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/apac-data-protection-lead-prudential",
    posted: "3d ago"
  },
  {
    title: "Manager, Third-Party Data Risk",
    company: "BNP Paribas",
    location: "Three Pacific Place, Admiralty",
    salary: "HK$55K–80K/mo",
    desc: "Manage third-party data risk programme for investment banking operations. Assess vendor data handling practices, cloud provider compliance, and cross-border data transfer risks.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/manager-third-party-data-risk-bnp",
    posted: "5d ago"
  },
  {
    title: "Responsible AI Lead",
    company: "Ping An OneConnect",
    location: "Cyberport, Hong Kong",
    salary: "HK$70K–95K/mo",
    desc: "Lead responsible AI programme for financial technology products across GBA. Implement fairness testing, explainability frameworks, and bias detection for credit scoring models.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/responsible-ai-lead-ping-an",
    posted: "1w ago"
  },
  {
    title: "VP, Information Governance",
    company: "UBS",
    location: "IFC, Central",
    salary: "HK$95K–130K/mo",
    desc: "Drive information governance strategy across wealth management and investment banking. Manage records retention, e-discovery readiness, and data classification programmes.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/vp-information-governance-ubs",
    posted: "2d ago"
  },
  {
    title: "Senior Analyst, Model Risk & AI Governance",
    company: "Bank of America",
    location: "Cheung Kong Center, Central",
    salary: "HK$50K–70K/mo",
    desc: "Support model risk management framework for AI/ML models in trading and credit risk. Conduct independent model validation and performance monitoring.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/senior-analyst-model-risk-boa",
    posted: "6d ago"
  },
  {
    title: "Data Governance Program Manager",
    company: "Société Générale",
    location: "Central, Hong Kong",
    salary: "HK$60K–85K/mo",
    desc: "Manage data governance programme across APAC operations. Coordinate data steward community, define data quality metrics, and implement regulatory data controls.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/data-governance-pm-socgen",
    posted: "4d ago"
  },
  {
    title: "Privacy & Data Governance Manager",
    company: "KPMG",
    location: "Prince's Building, Central",
    salary: "HK$60K–85K/mo",
    desc: "Lead privacy advisory engagements for TMT and financial services clients. Conduct privacy impact assessments, design data governance frameworks, and advise on cross-border data transfers.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/privacy-governance-manager-kpmg",
    posted: "1w ago"
  },
  {
    title: "AI Governance & Ethics Specialist",
    company: "SFC (Securities and Futures Commission)",
    location: "Sun Hung Kai Centre, Wan Chai",
    salary: "HK$60K–80K/mo",
    desc: "Support development of regulatory framework for AI use in Hong Kong's securities and futures industry. Conduct research on international AI governance standards and formulate guidance.",
    source: "LinkedIn",
    url: "https://www.linkedin.com/jobs/view/ai-governance-specialist-sfc",
    posted: "3d ago"
  },
  {
    title: "Data Protection & Compliance Consultant",
    company: "Robert Half",
    location: "Various, Hong Kong",
    salary: "HK$55K–80K/mo",
    desc: "Contract role supporting multiple clients on PDPO compliance, privacy impact assessments, and data governance framework design. Financial services experience required.",
    source: "eFinancialCareers",
    url: "https://www.efinancialcareers.hk/jobs/data-protection-compliance-robert-half",
    posted: "2d ago"
  },
  {
    title: "VP, Data & AI Risk Advisory",
    company: "Morgan Stanley",
    location: "ICC, West Kowloon",
    salary: "Not disclosed",
    desc: "Lead data and AI risk advisory for APAC institutional securities. Manage model governance, data quality assurance, and AI compliance programmes.",
    source: "eFinancialCareers",
    url: "https://www.efinancialcareers.hk/jobs/vp-data-ai-risk-morgan-stanley",
    posted: "5d ago"
  },
  {
    title: "Senior Data Governance Analyst - Wealth Management",
    company: "Julius Baer",
    location: "Jardine House, Central",
    salary: "HK$45K–65K/mo",
    desc: "Implement data governance standards for private banking client data. Manage data quality, classification, and PDPO compliance for wealth management operations.",
    source: "eFinancialCareers",
    url: "https://www.efinancialcareers.hk/jobs/data-governance-analyst-julius-baer",
    posted: "4d ago"
  },
  {
    title: "RegTech & Data Governance Lead",
    company: "Macquarie Group",
    location: "One IFC, Central",
    salary: "HK$80K–110K/mo",
    desc: "Lead regulatory technology strategy and data governance transformation. Deploy automated compliance monitoring and data lineage tracking for commodities and infrastructure businesses.",
    source: "eFinancialCareers",
    url: "https://www.efinancialcareers.hk/jobs/regtech-data-governance-macquarie",
    posted: "1w ago"
  },
  {
    title: "Data Governance & Privacy Senior Associate",
    company: "PwC Hong Kong",
    location: "Central, Hong Kong",
    salary: "HK$40K–55K/mo",
    desc: "Support data governance and privacy advisory engagements for banking and tech clients. Conduct data mapping, privacy impact assessments, and regulatory gap analysis.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=data-governance-privacy-pwc",
    posted: "3d ago"
  },
  {
    title: "Information Governance Analyst",
    company: "CLP Group",
    location: "Argyle Street, Kowloon",
    salary: "HK$35K–50K/mo",
    desc: "Support enterprise information governance programme for energy utility operations. Manage records management, data classification, and critical infrastructure cybersecurity compliance.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=info-governance-clp",
    posted: "5d ago"
  },
  {
    title: "AI Governance Coordinator",
    company: "Lenovo (APAC HQ)",
    location: "Quarry Bay, Hong Kong",
    salary: "HK$35K–50K/mo",
    desc: "Coordinate AI governance programmes across APAC product divisions. Support responsible AI reviews, bias testing documentation, and AI ethics committee operations.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=ai-governance-coordinator-lenovo",
    posted: "4d ago"
  },
  {
    title: "Junior Data Protection Officer",
    company: "Dah Sing Banking Group",
    location: "Des Voeux Road, Central",
    salary: "HK$28K–38K/mo",
    desc: "Support DPO function for banking group. Assist with PDPO compliance, data access requests, privacy training, and breach incident management.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=junior-dpo-dah-sing",
    posted: "1w ago"
  },
  {
    title: "Compliance & Data Governance Assistant Manager",
    company: "Kerry Logistics",
    location: "Kwai Chung, Hong Kong",
    salary: "HK$35K–48K/mo",
    desc: "Manage data governance and compliance programs for logistics operations. Ensure customs data integrity, cross-border data transfer compliance, and supply chain data governance.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=compliance-data-governance-kerry",
    posted: "6d ago"
  },
  {
    title: "Data Quality & Governance Analyst",
    company: "Hong Kong Airport Authority",
    location: "HKIA, Lantau",
    salary: "HK$32K–45K/mo",
    desc: "Support data quality and governance for airport operations systems. Manage data validation, anomaly detection, and master data management for passenger and cargo data.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=data-quality-governance-hkaa",
    posted: "3d ago"
  },
  {
    title: "Risk & Data Governance Manager",
    company: "Zurich Insurance (HK)",
    location: "The Lee Gardens, Causeway Bay",
    salary: "HK$55K–75K/mo",
    desc: "Lead data governance and operational risk management for insurance operations. Define data retention policies, privacy compliance standards, and AI model governance for underwriting.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=risk-data-governance-zurich",
    posted: "5d ago"
  },
  {
    title: "Digital Trust & AI Governance Consultant",
    company: "KPMG",
    location: "Prince's Building, Central",
    salary: "HK$40K–60K/mo",
    desc: "Support digital trust advisory practice. Conduct AI governance assessments, cybersecurity compliance reviews, and data privacy audits for financial services clients.",
    source: "Indeed",
    url: "https://hk.indeed.com/viewjob?jk=digital-trust-ai-kpmg",
    posted: "1w ago"
  }
];

