import os, json, re
from datetime import datetime, timezone, timedelta
from openai import OpenAI

client = OpenAI(
    api_key=os.environ["PERPLEXITY_API_KEY"],
    base_url="https://api.perplexity.ai"
)

HKT = timezone(timedelta(hours=8))
NOW = datetime.now(HKT).strftime("%Y-%m-%d %H:%M HKT")

# ── 1. NEWS DATA ────────────────────────────────────────────────────────────────
NEWS_PROMPT = """
You are a professional headhunter and career coach focused on the Hong Kong job market.
Search for the latest news (past 7 days) that would affect Hong Kong professionals,
especially those in Data Governance, AI Governance, Compliance, and Financial Services.

Return ONLY a valid JSON array (no markdown, no explanation) of news items.
Each item must have exactly these fields:
- headline: string (English or Traditional Chinese OK)
- date: string in YYYY-MM-DD format
- source: string (e.g. "SCMP", "Bloomberg", "HKMA")
- url: string (real working URL to the article)
- category: one of exactly: "POLICY & REGULATION", "CORPORATE", "TECHNOLOGY & AI",
  "FINANCIAL SECTOR", "TRADE & GEOPOLITICS", "US TARIFFS", "DATA GOVERNANCE & PRIVACY",
  "CHINA MAINLAND", "REAL ESTATE & COST", "GLOBAL", "LOCAL EMPLOYMENT", "FINTECH"
- impact: string (2-3 sentences explaining job market impact for HK professionals)
- sentiment: one of exactly: "positive", "negative", "neutral"

Include at least 15 items covering: HK macro data, US-China trade, AI regulation,
PDPO/GDPR updates, HKMA fintech policy, job vacancy stats, salary trends, GBA developments.
Include local Chinese-language news where relevant.
"""

news_response = client.chat.completions.create(
    model="sonar",
    messages=[
        {"role": "system", "content": "You are a JSON-only response bot. Return only valid JSON arrays, no markdown fences, no explanation text."},
        {"role": "user", "content": NEWS_PROMPT}
    ],
    temperature=0.1
)

# ── 2. JOBS DATA ────────────────────────────────────────────────────────────────
JOBS_PROMPT = """
Search for current job openings in Hong Kong for Data Governance, AI Governance,
Data Privacy, DPO (Data Protection Officer), Chief Data Officer, Data Quality,
and related compliance/risk roles.

Search across: JobsDB Hong Kong, LinkedIn Hong Kong, eFinancialCareers Hong Kong, Indeed Hong Kong.

Return ONLY a valid JSON array of job listings with exactly these fields:
- title: string (job title)
- company: string
- location: string (e.g. "Hong Kong", "Kowloon", "Remote")
- salary: string (e.g. "HK$35,000 - 50,000/month" or "Not disclosed")
- posted: string (e.g. "2 days ago", "1 week ago")
- url: string (direct link to the job posting)
- source: one of exactly: "JobsDB", "LinkedIn", "eFinancialCareers", "Indeed"
- desc: string (2 sentences describing the role and key requirements)

Include at least 20 listings. Mix seniority levels (analyst, manager, VP, MD).
"""

jobs_response = client.chat.completions.create(
    model="sonar",
    messages=[
        {"role": "system", "content": "You are a JSON-only response bot. Return only valid JSON arrays, no markdown fences, no explanation text."},
        {"role": "user", "content": JOBS_PROMPT}
    ],
    temperature=0.1
)

# ── 3. Parse responses ──────────────────────────────────────────────────────────
def extract_json(text):
    # Strip markdown fences if model added them despite instructions
    text = re.sub(r'^```json\s*', '', text.strip())
    text = re.sub(r'```$', '', text.strip())
    return json.loads(text)

news_data = extract_json(news_response.choices[0].message.content)
jobs_data = extract_json(jobs_response.choices[0].message.content)

# ── 4. Write data.js ──────────────────────────────────────────────────────────
output = f"""// Auto-generated by update_data.py — DO NOT EDIT MANUALLY
// Last updated: {NOW}

const LAST_UPDATED = "{NOW}";

const NEWS_DATA = {json.dumps(news_data, ensure_ascii=False, indent=2)};

const JOBS_DATA = {json.dumps(jobs_data, ensure_ascii=False, indent=2)};
"""

with open("data.js", "w", encoding="utf-8") as f:
    f.write(output)

print(f"✅ data.js updated at {NOW}")
print(f"   News items: {len(news_data)}")
print(f"   Job listings: {len(jobs_data)}")
